-- さかいそろばん教室 セキュリティ優先スキーマ
-- Supabase SQL Editorで一括実行してください。
create extension if not exists pgcrypto;
create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;

do $$ begin
  create type public.app_role as enum ('guardian', 'teacher', 'admin');
exception when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role public.app_role not null default 'guardian',
  display_name text not null,
  created_at timestamptz not null default now()
);

-- 保護者1人に複数生徒を紐付ける1対多。
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  guardian_id uuid not null references public.profiles(id) on delete restrict,
  name text not null,
  classroom text not null check (classroom in ('福沼教室', '穂波教室')),
  grade text not null,
  regular text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- LINEユーザーIDはサーバー側HMAC値だけ保存し、平文は保存しない。
create table if not exists private.guardian_line_identities (
  guardian_id uuid primary key references public.profiles(id) on delete cascade,
  line_user_id_hmac text not null unique,
  linked_at timestamptz not null default now(),
  last_authenticated_at timestamptz
);

-- 初回本人確認用。コード本体は保存せずハッシュだけ保存する。
create table if not exists private.guardian_link_codes (
  id uuid primary key default gen_random_uuid(),
  guardian_id uuid not null references public.profiles(id) on delete cascade,
  code_hash text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.absence_records (
  id uuid primary key default gen_random_uuid(),
  student_id bigint not null references public.students(id) on delete restrict,
  absence_date date not null,
  reason text not null check (char_length(reason) between 1 and 200),
  wants_makeup boolean not null default false,
  makeup_date date,
  makeup_classroom text check (makeup_classroom is null or makeup_classroom in ('福沼教室', '穂波教室')),
  makeup_slot text check (makeup_slot is null or makeup_slot in ('16:00', '17:00', '18:00')),
  status text not null default 'none' check (status in ('none', 'pending', 'reserved', 'completed')),
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated always as identity primary key,
  actor_id uuid,
  actor_role public.app_role,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  table_name text not null,
  record_id text not null,
  student_id bigint,
  old_data jsonb,
  new_data jsonb,
  ip_address inet,
  request_id text,
  changed_at timestamptz not null default now()
);

create index if not exists students_guardian_id_idx on public.students(guardian_id);
create index if not exists students_name_idx on public.students(name);
create index if not exists absence_records_student_id_idx on public.absence_records(student_id);
create index if not exists absence_records_absence_date_idx on public.absence_records(absence_date);
create index if not exists absence_records_makeup_date_idx on public.absence_records(makeup_date);
create index if not exists audit_logs_changed_at_idx on public.audit_logs(changed_at desc);
create index if not exists audit_logs_student_id_idx on public.audit_logs(student_id);
create index if not exists guardian_line_identity_hmac_idx on private.guardian_line_identities(line_user_id_hmac);
create index if not exists guardian_link_codes_expiry_idx on private.guardian_link_codes(expires_at);

create or replace function private.current_user_role()
returns public.app_role language sql stable security definer
set search_path = public, pg_temp
as $$ select role from public.profiles where id = (select auth.uid()) $$;
revoke all on function private.current_user_role() from public, anon;
grant execute on function private.current_user_role() to authenticated;

create or replace function private.is_staff()
returns boolean language sql stable security definer
set search_path = public, pg_temp
as $$ select coalesce(private.current_user_role() in ('teacher', 'admin'), false) $$;
revoke all on function private.is_staff() from public, anon;
grant execute on function private.is_staff() to authenticated;

create or replace function private.is_admin()
returns boolean language sql stable security definer
set search_path = public, pg_temp
as $$ select coalesce(private.current_user_role() = 'admin', false) $$;
revoke all on function private.is_admin() from public, anon;
grant execute on function private.is_admin() to authenticated;

alter table public.profiles enable row level security;
alter table public.students enable row level security;
alter table public.absence_records enable row level security;
alter table public.audit_logs enable row level security;

revoke all on public.profiles, public.students, public.absence_records, public.audit_logs from anon;
revoke all on public.profiles, public.students, public.absence_records, public.audit_logs from authenticated;
grant select on public.profiles, public.students, public.audit_logs to authenticated;
grant select, insert, update, delete on public.absence_records to authenticated;
grant insert, update, delete on public.students to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists profiles_select_own_or_staff on public.profiles;
create policy profiles_select_own_or_staff on public.profiles for select to authenticated
using ((select auth.uid()) is not null and (id = (select auth.uid()) or (select private.is_admin())));

drop policy if exists students_select_own_or_staff on public.students;
create policy students_select_own_or_staff on public.students for select to authenticated
using ((select auth.uid()) is not null and (guardian_id = (select auth.uid()) or (select private.is_staff())));

drop policy if exists students_admin_insert on public.students;
create policy students_admin_insert on public.students for insert to authenticated
with check ((select private.is_admin()));
drop policy if exists students_admin_update on public.students;
create policy students_admin_update on public.students for update to authenticated
using ((select private.is_admin())) with check ((select private.is_admin()));
drop policy if exists students_admin_delete on public.students;
create policy students_admin_delete on public.students for delete to authenticated
using ((select private.is_admin()));

drop policy if exists absence_guardian_insert_own_child on public.absence_records;
create policy absence_guardian_insert_own_child on public.absence_records for insert to authenticated
with check (
  (select private.current_user_role()) = 'guardian'
  and created_by = (select auth.uid())
  and exists (
    select 1 from public.students s
    where s.id = absence_records.student_id and s.guardian_id = (select auth.uid())
  )
  and status in ('none', 'reserved')
  and (
    (wants_makeup = false and status = 'none' and makeup_date is null and makeup_classroom is null and makeup_slot is null)
    or
    (wants_makeup = true and status = 'reserved' and makeup_date is not null and makeup_classroom is not null and makeup_slot is not null)
  )
);

-- 保護者には過去連絡一覧も返さず、先生・管理者のみ閲覧。
drop policy if exists absence_staff_select on public.absence_records;
create policy absence_staff_select on public.absence_records for select to authenticated
using ((select private.is_staff()));

drop policy if exists absence_staff_update on public.absence_records;
create policy absence_staff_update on public.absence_records for update to authenticated
using ((select private.is_staff())) with check ((select private.is_staff()));

create or replace function private.protect_absence_ownership()
returns trigger language plpgsql
set search_path = public, pg_temp
as $$
begin
  if new.student_id is distinct from old.student_id
     or new.created_by is distinct from old.created_by
     or new.created_at is distinct from old.created_at then
    raise exception 'ownership fields are immutable';
  end if;
  return new;
end;
$$;
revoke all on function private.protect_absence_ownership() from public, anon, authenticated;

drop trigger if exists absence_protect_ownership on public.absence_records;
create trigger absence_protect_ownership
before update on public.absence_records
for each row execute function private.protect_absence_ownership();

drop policy if exists absence_admin_delete on public.absence_records;
create policy absence_admin_delete on public.absence_records for delete to authenticated
using ((select private.is_admin()));

drop policy if exists audit_staff_select on public.audit_logs;
create policy audit_staff_select on public.audit_logs for select to authenticated
using ((select private.is_staff()));

create or replace function private.prevent_audit_mutation()
returns trigger language plpgsql
set search_path = public, pg_temp
as $$
begin
  raise exception 'audit logs are immutable';
end;
$$;
revoke all on function private.prevent_audit_mutation() from public, anon, authenticated;

drop trigger if exists audit_logs_immutable on public.audit_logs;
create trigger audit_logs_immutable
before update or delete on public.audit_logs
for each row execute function private.prevent_audit_mutation();

create or replace function private.write_audit_log()
returns trigger language plpgsql security definer
set search_path = public, pg_temp
as $$
declare
  v_role public.app_role;
  v_student_id bigint;
  v_record_id text;
  v_headers jsonb;
  v_ip inet;
  v_request_id text;
begin
  select role into v_role from public.profiles where id = (select auth.uid());
  begin
    v_headers := nullif(current_setting('request.headers', true), '')::jsonb;
    v_ip := split_part(coalesce(v_headers->>'x-forwarded-for', v_headers->>'cf-connecting-ip'), ',', 1)::inet;
    v_request_id := coalesce(v_headers->>'x-request-id', v_headers->>'cf-ray');
  exception when others then
    v_ip := null;
    v_request_id := null;
  end;
  v_student_id := case when tg_table_name = 'students' then coalesce(new.id, old.id) else coalesce(new.student_id, old.student_id) end;
  v_record_id := coalesce(new.id::text, old.id::text);
  insert into public.audit_logs(actor_id, actor_role, action, table_name, record_id, student_id, old_data, new_data, ip_address, request_id)
  values (
    (select auth.uid()), v_role, tg_op, tg_table_name, v_record_id, v_student_id,
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) end,
    v_ip, v_request_id
  );
  return coalesce(new, old);
end;
$$;
revoke all on function private.write_audit_log() from public, anon, authenticated;

drop trigger if exists audit_students_changes on public.students;
create trigger audit_students_changes after insert or update or delete on public.students
for each row execute function private.write_audit_log();
drop trigger if exists audit_absence_changes on public.absence_records;
create trigger audit_absence_changes after insert or update or delete on public.absence_records
for each row execute function private.write_audit_log();

create or replace function private.touch_updated_at()
returns trigger language plpgsql set search_path = public, pg_temp
as $$ begin new.updated_at = now(); return new; end; $$;
revoke all on function private.touch_updated_at() from public, anon, authenticated;
drop trigger if exists students_touch_updated_at on public.students;
create trigger students_touch_updated_at before update on public.students
for each row execute function private.touch_updated_at();
drop trigger if exists absence_touch_updated_at on public.absence_records;
create trigger absence_touch_updated_at before update on public.absence_records
for each row execute function private.touch_updated_at();

create or replace function public.teacher_dashboard_counts(
  p_classroom text default null, p_date date default null, p_search text default null
) returns jsonb language plpgsql stable security invoker
set search_path = public, pg_temp
as $$
declare result jsonb;
begin
  if not (select private.is_staff()) then raise exception 'forbidden'; end if;
  select jsonb_build_object(
    'today_absences', count(*) filter (where ar.absence_date = current_date),
    'today_makeups', count(*) filter (where ar.makeup_date = current_date and ar.status = 'reserved'),
    'pending_makeups', count(*) filter (where ar.status = 'pending')
  ) into result
  from public.absence_records ar join public.students s on s.id = ar.student_id
  where (p_classroom is null or s.classroom = p_classroom)
    and (p_date is null or ar.absence_date = p_date or ar.makeup_date = p_date)
    and (p_search is null or s.name ilike '%' || p_search || '%');
  return result;
end;
$$;
revoke all on function public.teacher_dashboard_counts(text, date, text) from public, anon;
grant execute on function public.teacher_dashboard_counts(text, date, text) to authenticated;

-- profilesのrole設定はDashboard/安全な管理処理から実施。
-- service_role keyはRLSを回避するためブラウザへ絶対に置かない。
-- private.guardian_line_identities / guardian_link_codes は認証交換APIだけがservice_roleで操作する。
